<?php

use Illuminate\Database\Seeder;

class CampoObraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tec_campos')->insert([
            'nome'                => 'nome',
            'titulo'              => 'Nome',
            'descricao'           => 'Nome',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-8',
            'tamanhoi'            => 'col-md-5',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'align-justify',
            'tipo'                => 'text',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '',
            'ordem'               => 10,
          ]);
    
          DB::table('tec_campos')->insert([
            'nome'                => 'pessoa_id',
            'titulo'              => 'Cliente',
            'descricao'           => 'Cliente',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-4',
            'tamanhoi'            => '',
            'ehformulario'        => 'S',
            'ehgrid'              => 'N',
            'icone'               => 'user',
            'tipo'                => 'text',
            'componente'          => 'select',
            'tabelareferencia'     => 'cad_pessoas',
            'observacao'          => '',
            'obrigatorio'         => 'required',
            'tabela_id'           => 2,
            'mascara'             => '',
            'ordem'               => 20,
          ]);

          DB::table('tec_campos')->insert([
            'nome'                => 'prioridade_id',
            'titulo'              => 'Prioridade',
            'descricao'           => 'Prioridade',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => '',
            'ehformulario'        => 'S',
            'ehgrid'              => 'N',
            'icone'               => 'angle-double-up',
            'tipo'                => 'text',
            'componente'          => 'select',
            'tabelareferencia'     => 'cad_prioridade',
            'observacao'          => '',
            'obrigatorio'         => 'required',
            'tabela_id'           => 2,
            'mascara'             => '',
            'ordem'               => 23,
          ]);

          DB::table('tec_campos')->insert([
            'nome'                => 'tipo_id',
            'titulo'              => 'Tipo',
            'descricao'           => 'Tipo da obra',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => '',
            'ehformulario'        => 'S',
            'ehgrid'              => 'N',
            'icone'               => 'bookmark',
            'tipo'                => 'text',
            'componente'          => 'select',
            'tabelareferencia'     => 'cad_tipos',
            'observacao'          => '',
            'obrigatorio'         => 'required',
            'tabela_id'           => 2,
            'mascara'             => '',
            'ordem'               => 26,
          ]);
    
          DB::table('tec_campos')->insert([
            'nome'                => 'valororcamento',
            'titulo'              => 'Valor orçamento',
            'descricao'           => 'Valor orçamento',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => 'col-md-2',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'dollar-sign',
            'tipo'                => 'number',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '',
            'ordem'               => 30,
          ]);
    
          DB::table('tec_campos')->insert([
            'nome'                => 'valordisponivel',
            'titulo'              => 'Valor disponível',
            'descricao'           => 'Valor disponível',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => 'col-md-2',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'dollar-sign',
            'tipo'                => 'number',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '',
            'somenteleitura'      => 'readonly',
            'ordem'               => 40,
          ]);
    
          DB::table('tec_campos')->insert([
            'nome'                => 'valorutilizado',
            'titulo'              => 'Valor utilizado',
            'descricao'           => 'Valor utilizado',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => 'col-md-2',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'dollar-sign',
            'tipo'                => 'number',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '',
            'somenteleitura'      => 'readonly',
            'ordem'               => 50,
          ]);
    
          DB::table('tec_campos')->insert([
            'nome'                => 'valorrecebido',
            'titulo'              => 'Valor recebido',
            'descricao'           => 'Valor recebido',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => 'col-md-2',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'dollar-sign',
            'tipo'                => 'number',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '',
            'somenteleitura'      => 'readonly',
            'ordem'               => 60,
          ]);
    
          DB::table('tec_campos')->insert([
            'nome'                => 'valorpendente',
            'titulo'              => 'Valor pendente',
            'descricao'           => 'Valor pendente',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => 'col-md-2',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'dollar-sign',
            'tipo'                => 'number',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '',
            'somenteleitura'      => 'readonly',
            'ordem'               => 70,
          ]);

          DB::table('tec_campos')->insert([
            'nome'                => 'previsaoduracao',
            'titulo'              => 'Horas previstas',
            'descricao'           => 'Horas previstas',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => 'col-md-2',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'calendar-alt',
            'tipo'                => 'number',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '',
            'ordem'               => 80,
          ]);
    
          DB::table('tec_campos')->insert([
            'nome'                => 'duracaoatual',
            'titulo'              => 'Horas utilizadas',
            'descricao'           => 'Horas utilizadas',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => 'col-md-2',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'calendar-alt',
            'tipo'                => 'number',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '',
            'somenteleitura'      => 'readonly',
            'ordem'               => 90,
          ]);      
    
          DB::table('tec_campos')->insert([
            'nome'                => 'duracaoexcedente',
            'titulo'              => 'Horas excedentes',
            'descricao'           => 'Horas excedentes',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => 'col-md-2',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'calendar-alt',
            'tipo'                => 'number',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '',
            'somenteleitura'      => 'readonly',
            'ordem'               => 100,
          ]);
    
          DB::table('tec_campos')->insert([
            'nome'                => 'previsaoinicio',
            'titulo'              => 'Previsão de início',
            'descricao'           => 'Previsão de início',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => 'col-md-2',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'calendar-alt',
            'tipo'                => 'text',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '00/00/0000',
            'ordem'               => 110,
          ]);
    
          DB::table('tec_campos')->insert([
            'nome'                => 'previsaotermino',
            'titulo'              => 'Previsão de término',
            'descricao'           => 'Previsão de término',
            'tamanho'             => '',
            'tamanhof'            => 'col-md-2',
            'tamanhoi'            => 'col-md-2',
            'ehformulario'        => 'S',
            'ehgrid'              => 'S',
            'icone'               => 'calendar-alt',
            'tipo'                => 'text',
            'componente'          => 'input',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '00/00/0000',
            'ordem'               => 120,
          ]);
    
          DB::table('tec_campos')->insert([
            'nome'                => 'observacao',
            'titulo'              => 'Observação',
            'descricao'           => 'Observação da obra',
            'tamanho'             => '5',
            'tamanhof'            => 'col-md-12',
            'tamanhoi'            => '',
            'ehformulario'        => 'S',
            'ehgrid'              => 'N',
            'icone'               => 'align-justify',
            'tipo'                => '',
            'componente'          => 'textarea',
            'tabelareferencia'     => '',
            'observacao'          => '',
            'obrigatorio'         => '',
            'tabela_id'           => 2,
            'mascara'             => '',
            'ordem'               => 130,
          ]);
    }
}
